### ISSUE TITLE
How do we style comma delimited guard statements?

### ISSUE THREAD

**Issue by wingchi** [IntrepidPursuits/swift-style-guide#15]
This can be done in a few ways, for example:

```
guard
  let someVar = someClass.method(),
  someOtherVar = someOtherClass.otherMethod()
  else { return }
```

```
guard
  let someVar = someClass.method(),
  let someOtherVar = someOtherClass.otherMethod()
  else { return }
```

**Comment by loganwright** [comment]
Whatever we do here, it should also apply to `if` statements.  I'm personally partial to the `let` on each statement for the way it aligns, but I also like the brevity of omitting it.

+1 for 2 from me

**Comment by paulrolfe** [comment]
I agree with @LoganWright here. I prefer the second one, but both have their merits.

**Comment by loganwright** [comment]
I think we'll move forward w/ `let` on each line. Thanks for the tiebreaker @paulrolfe

**Comment by alexpersian** [comment]
This is now covered in the [style guide](https://github.com/IntrepidPursuits/swift-style-guide#guard-statements), so I'm closing this issue.
