### ISSUE TITLE
Guidelines on Rx styling and usage

### ISSUE THREAD

**Issue by alexpersian** [IntrepidPursuits/swift-style-guide#31]
Our style guide should contain some style preferences for working with RxSwift. If needed it would be good to have some best practices for when and how to use it as well. Unless that's more fitting for Sherpa.

For example:

```swift
someState.asObservable().distinctUntilChanged()
    .scan([]) { (previousState, nextState) in
        return Array(previousStates + [nextState]).suffix(2) 
    }
    .subscribeNext { [weak self] (lastTwoStates) in
        guard
            let oldState = lastTwoStates.first,
            let newState = lastTwoStates.last
            else { return }
        self?.handleSomething(oldState, newState: newState)
    }.disposed(by: bag)
```
vs.
```swift
someState
    .asObservable()
    .distinctUntilChanged()
    .scan([]) { (previousState, nextState) in
        return Array(previousStates + [nextState]).suffix(2) }
    .subscribeNext { [weak self] (lastTwoStates) in
        guard
            let oldState = lastTwoStates.first,
            let newState = lastTwoStates.last
            else { return }
        self?.handleSomething(oldState, newState: newState)
    }.disposed(by: bag)
```
or some other style entirely.

**Comment by Benuuu** [comment]
It seems like this generally becomes, "how should we handle the style of chaining function calls?"

Your examples appear to a bit inconsistent within themselves.  In my experience, I've grown to like the following example
```
someState
    .asObservable()
    .distinctUntilChanged()
    .scan([]) { (previousState, nextState) in
        return Array(previousStates + [nextState]).suffix(2)
    }
    .subscribeNext { [weak self] (lastTwoStates) in
        guard
            let oldState = lastTwoStates.first,
            let newState = lastTwoStates.last
            else { return }
        self?.handleSomething(oldState, newState: newState)
    }
    .disposed(by: bag)
```

This follows a similar style to the following:
> For functions with many arguments, specify each arg on a new line and the ) on the final line.

https://github.com/IntrepidPursuits/swift-style-guide#calling

> To keep it clean, use a new line for each argument and avoid trailing closures.

https://github.com/IntrepidPursuits/swift-style-guide#like-this-5


Maybe we could call it, "Chaining Functions"
> If you are chaining functions together, specify each separate function on a new line beginning with the `.`

We might also want something like:
> When chaining, avoid mixing property accessors and function.
